[package]
name = "citator"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["David Conrad <dconrad@gmail.com>"]
license = "MIT-0"
description = "A package to handle legal citations to cases, statutes, and other authorities."